name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t project-template:latest .
    - name: Push to Docker Hub
      run: echo "Push to Docker Hub instructions"
